### ISSUE TITLE
Add Support For Optional Encryption

### ISSUE THREAD

**Issue by derks** [disaster37/rancher-backup#10]
Would be nice to have the ability to GPG encrypt the backup with a passphrase, before it gets uploaded to the destination backend service.

**Comment by disaster37** [comment]
Hi, I add enhance about this (only on develop branch, aka docker develop tag). Any feedback is welcome.

1. Generate gpg key on your PC `gpg --gen-key`
2. Copy GPG keys on your rancher node
3. Mount GPG folder on rancher-backup container in `/opt/backup/.gnupg`
4. Add the following environment variable on rancher-backup service
* `BACKUP_DUPLICITY_encrypt-key` : the id GPG key that you have generated (-> gpg --list-keys)
* `PASSPHRASE`: the passphrase you have setted when you have generated the gpg key.

**Comment by derks** [comment]
@disaster37 I should have mentioned in my original post... it would be ideal in our case to be able to use `symmetric cipher` option rather than having to volume mount a key:

```
 -c, --symmetric            encryption only with symmetric cipher
```


This would allow the backup configuration to only require an environment variable for the `PASSPHRASE`, and not complicate it with volume mounts for a private key.  Would that be possible?

**Comment by disaster37** [comment]
hi,

I am sorry but I doesn't found any other option like GPG to crypt backup with duplicity http://duplicity.nongnu.org/duplicity.1.html ?

have you found option `--symetric` on duplicity documentation ?

**Comment by lasley** [comment]
Why not just store the public key as an environment variable & import the key via a script? This would allow for the filesystem operations to be skipped, and I don't see any harm in a public key being exposed - particularly with the password already being there.

**Comment by derks** [comment]
Public key as an environment variable could work... and now that I think of it, putting the private key in a secrets file if necessary could work as well.  I'll move to the next thing.. I really don't have any idea how to test the develop branch in Rancher?

**Comment by lasley** [comment]
I just switched over - you can use the upgrade option on the service (not the stack) in order to update the image from the versioned to the develop tag. You'll also need to add the env variables and mount the drive in there as well.

**Comment by lasley** [comment]
Also why encrypt with the private? The beauty of PGP is that you only need the public for encryption, so you don't have to expose the private parts anywhere in your stacks.

**Comment by disaster37** [comment]
@lasley your are right about encrypt with public key. But I my test, duplicity crash if I not exposed public and private key. So maybe my test is to bad, or maybe Duplicity use private key to decrypt the metadata about last backup before perform the current backup ?

**Comment by disaster37** [comment]
No news, so I consider is closed. You can reopen it if needed.
