### ISSUE TITLE
Error: environment is not a valid type

### ISSUE THREAD

**Issue by Willzyc** [disaster37/rancher-backup#11]
I get an error every time I run the backup. I run the backup.py script from the command line as root.
The database dumps are working fine, but after the last one finished I got this error:

2017-04-18 12:20:57,692 - ERROR - Unattented error occur : environment is not a
valid type
2017-04-18 12:20:57,692 - ERROR - Traceback (most recent call last):
  File "backup.py", line 141, in <module>
    listStacks = rancherService.getStacks()
  File "/app/fr/webcenter/backup/Rancher.py", line 79, in getStacks
    listEnvironments = self._client.list('environment')
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 381, in list
    raise ClientApiError(type + ' is not a valid type')
ClientApiError: environment is not a valid type

I have only 1 environment. I renamed the default one to "production", but I do not know if this matters.

I also use only host volume mounts. The version is 1.0.2 from the catalog. Upgrading to version 2.0.0-2 results in exiting after the startup with these logs:

18.4.2017 14:53:58[cont-init.d] 00-welcome.sh: exited 0.
18.4.2017 14:53:58[cont-init.d] 01-gen-confd-config.sh: executing...
18.4.2017 14:53:58[cont-init.d] 01-gen-confd-config.sh: exited 0.
18.4.2017 14:53:58[cont-init.d] 02-init-confd.sh: executing...
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO Backend set to env
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO Starting confd
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO Backend nodes set to
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO Target config /etc/services.d/cron/run out of sync
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO Target config /etc/services.d/cron/run has been updated
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO /opt/backup/config/rancher-backup.yml has UID 1000 should be 1001
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO /opt/backup/config/rancher-backup.yml has GID 101 should be 1001
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO /opt/backup/config/rancher-backup.yml has mode -rw-rw---- should be -rw-r--r--
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO /opt/backup/config/rancher-backup.yml has md5sum 32fe12c98e31ab98e7c88502b8a9d60a should be b2b4a7a9e12e8c8a1478bfef3a0b2d19
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO Target config /opt/backup/config/rancher-backup.yml out of sync
18.4.2017 14:53:582017-04-18T12:53:58Z a41f250d38f3 /opt/confd/bin/confd[343]: INFO Target config /opt/backup/config/rancher-backup.yml has been updated
18.4.2017 14:53:58[cont-init.d] 02-init-confd.sh: exited 0.
18.4.2017 14:53:58[cont-init.d] 04-run-backup.sh: executing...
18.4.2017 14:53:582017-04-18 12:53:58,395 - ERROR - Somthing wrong on your config file:
18.4.2017 14:53:58[cont-init.d] 04-run-backup.sh: exited 1.
18.4.2017 14:53:58[cont-finish.d] executing container finish scripts...
18.4.2017 14:53:58[cont-finish.d] done.
18.4.2017 14:53:58[s6-finish] syncing disks.
18.4.2017 14:53:59[s6-finish] sending all processes the TERM signal.
18.4.2017 14:54:02[s6-finish] sending all processes the KILL signal and exiting.

If you need more information about my setup, feel free to ask.

Willzyc

**Comment by disaster37** [comment]
You need to upgrade to 2.0.0-2.
But to do that you need to change all your environment variable to config rancher-backup. There are many breaking change.

`ERROR - Somthing wrong on your config file` mean you have not set all parameters.

**Comment by Willzyc** [comment]
Now I am getting an error, that the python script can not connect to the docker daemon

24.4.2017 21:20:20[cont-init.d] 00-welcome.sh: exited 0.
24.4.2017 21:20:20[cont-init.d] 01-gen-confd-config.sh: executing...
24.4.2017 21:20:20[cont-init.d] 01-gen-confd-config.sh: exited 0.
24.4.2017 21:20:20[cont-init.d] 02-init-confd.sh: executing...
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO Backend set to env
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO Starting confd
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO Backend nodes set to
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO Target config /etc/services.d/cron/run out of sync
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO Target config /etc/services.d/cron/run has been updated
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO /opt/backup/config/rancher-backup.yml has UID 1000 should be 1001
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO /opt/backup/config/rancher-backup.yml has GID 101 should be 1001
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO /opt/backup/config/rancher-backup.yml has mode -rw-rw---- should be -rw-r--r--
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO /opt/backup/config/rancher-backup.yml has md5sum 32fe12c98e31ab98e7c88502b8a9d60a should be f8c4d0a9198c9b1db46fcc1fab30a2fa
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO Target config /opt/backup/config/rancher-backup.yml out of sync
24.4.2017 21:20:202017-04-24T19:20:20Z c70b3e5a4c9e /opt/confd/bin/confd[343]: INFO Target config /opt/backup/config/rancher-backup.yml has been updated
24.4.2017 21:20:20[cont-init.d] 02-init-confd.sh: exited 0.
24.4.2017 21:20:20[cont-init.d] 04-run-backup.sh: executing...
24.4.2017 21:20:202017-04-24 19:20:20,494 - INFO - Rancher URL: xxxxx <- is correct
24.4.2017 21:20:202017-04-24 19:20:20,495 - INFO - Rancher key: xxxxx <- also correct
24.4.2017 21:20:202017-04-24 19:20:20,495 - INFO - Rancher secret: XXXX
24.4.2017 21:20:202017-04-24 19:20:20,495 - INFO - Backup path: /backup
24.4.2017 21:20:202017-04-24 19:20:20,495 - INFO - Backup target path: /
24.4.2017 21:20:202017-04-24 19:20:20,495 - INFO - Backend to receive remote backup: sftp://user@example.com
24.4.2017 21:20:202017-04-24 19:20:20,495 - INFO - Backup full frequency: 7D
24.4.2017 21:20:202017-04-24 19:20:20,495 - INFO - Backup full to keep: 3
24.4.2017 21:20:202017-04-24 19:20:20,495 - INFO - Backup incremental chain to keep: 1
24.4.2017 21:20:202017-04-24 19:20:20,495 - INFO - Volume size: 200
24.4.2017 21:20:202017-04-24 19:20:20,684 - INFO - Can't grab Rancher database settings from API, try to grab it from config file
24.4.2017 21:20:202017-04-24 19:20:20,684 - INFO - Start to initialize Duplicity...
24.4.2017 21:20:212017-04-24 19:20:21,177 - INFO - No backup found (probably the first) or already initialized
24.4.2017 21:20:212017-04-24 19:20:21,177 - INFO - Start to dump databases...
24.4.2017 21:20:222017-04-24 19:20:22,398 - INFO - Found 'cloud/mysql' to do dumping
24.4.2017 21:20:222017-04-24 19:20:22,405 - INFO - Found 'mail/mysql' to do dumping
24.4.2017 21:20:222017-04-24 19:20:22,411 - INFO - Dumping cloud/mysql in /backup/dump/cloud/mysql
24.4.2017 21:20:222017-04-24 19:20:22,420 - ERROR - Unattented error occur : Error when run cmd docker pull mariadb:latest : Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/
24.4.2017 21:20:22
24.4.2017 21:20:22Cannot connect to the Docker daemon. Is the docker daemon running on this host?
24.4.2017 21:20:22
24.4.2017 21:20:222017-04-24 19:20:22,420 - ERROR - Traceback (most recent call last):
24.4.2017 21:20:22  File "/opt/backup/backup.py", line 223, in <module>
24.4.2017 21:20:22    backupService.runDump(listDump)
24.4.2017 21:20:22  File "/opt/backup/fr/webcenter/backup/Backup.py", line 121, in runDump
24.4.2017 21:20:22    commandService.runCmd("docker pull %s" % dump['image'])
24.4.2017 21:20:22  File "/opt/backup/fr/webcenter/backup/Command.py", line 37, in runCmd
24.4.2017 21:20:22    raise Exception("Error when run cmd " + cmd + " : " + out + "\n" + err)
24.4.2017 21:20:22Exception: Error when run cmd docker pull mariadb:latest : Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/
24.4.2017 21:20:22
24.4.2017 21:20:22Cannot connect to the Docker daemon. Is the docker daemon running on this host?
24.4.2017 21:20:22
24.4.2017 21:20:22
24.4.2017 21:20:22[cont-init.d] 04-run-backup.sh: exited 1.
24.4.2017 21:20:22[cont-finish.d] executing container finish scripts...
24.4.2017 21:20:22[cont-finish.d] done.
24.4.2017 21:20:22[s6-finish] syncing disks.
24.4.2017 21:20:25[s6-finish] sending all processes the TERM signal.
24.4.2017 21:20:28[s6-finish] sending all processes the KILL signal and exiting.

When I init the image with /bin/bash and I run docker ps, it works.

This time I also tried it with privileged mode and mounting the docker.sock. Same results.

**Comment by disaster37** [comment]
Hi,
I think it's because I externalize the docker engine on sidekick container (micro service pattern).
A good way is to add custom catalog https://github.com/disaster37/community-catalog.git with branch feature/rancherBackup (pull request not yet merged on community catalog). Then create a new stack from the custom catalog "rancher-backup". It will create for you all stuff needed by the new pattern.

**Comment by disaster37** [comment]
No news about this. On branch develop, it now display more usefull information when somethinks wrong.

**Comment by dizlexik** [comment]
@disaster37 How exactly does the DOCKER_HOST environment variable get its value? I'm trying to run this by linking my own DIND container but my rancher-backup container environment never contains DOCKER_HOST, only variables such as `DOCKER_PORT="tcp://172.17.0.5:2375"` which would actually be fine if I could somehow do `export DOCKER_HOST=$DOCKER_PORT`, but that would be a lame hack. Just curious to know how I can get this working running outside of a Rancher environment. Thanks.

**Comment by dizlexik** [comment]
Sorry, I think that was a dumb question. I can just set DOCKER_HOST during `docker run -e ...`. Sorry to bother you :/
