### ISSUE TITLE
Duplicity Options not working

### ISSUE THREAD

**Issue by gregori-goossens** [disaster37/rancher-backup#15]
Hi,

i think there is a little mistake in template : 
rancher-backup/root/opt/confd/etc/templates/rancher-backup.yml.tmpl

missing / char in following lines (line 61,62): 
```
{{- if (exists "duplicity/options")}}
  options: "{{getv "duplicity/options"}}"
```

must be : 
```
{{- if (exists "/duplicity/options")}}
  options: "{{getv "/duplicity/options"}}"
```

thanks for your work.

**Comment by disaster37** [comment]
Hum, yes you are right. I will fix it ASAP.

Thanks for that ;)

**Comment by disaster37** [comment]
It's merge on develop branch, thx a lot.
