### ISSUE TITLE
Backup craching and exiting

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [disaster37/rancher-backup#17]
```
17/07/2017 09:59:022017-07-17 06:59:02,481 - INFO - Dumping PostgresCluster/Master in /backup/dump/PostgresCluster/Master
17/07/2017 09:59:022017-07-17 06:59:02,481 - ERROR - Unattented error occur : 'NoneType' object is not iterable
17/07/2017 09:59:022017-07-17 06:59:02,481 - ERROR - Traceback (most recent call last):
17/07/2017 09:59:02  File "/opt/backup/backup.py", line 224, in <module>
17/07/2017 09:59:02    backupService.runDump(listDump)
17/07/2017 09:59:02  File "/opt/backup/fr/webcenter/backup/Backup.py", line 107, in runDump
17/07/2017 09:59:02    for env in dump['environments']:
17/07/2017 09:59:02TypeError: 'NoneType' object is not iterable
17/07/2017 09:59:02
17/07/2017 09:59:02[cont-init.d] 04-run-backup.sh: exited 1.
17/07/2017 09:59:02[cont-finish.d] executing container finish scripts...
17/07/2017 09:59:02[cont-finish.d] done.
17/07/2017 09:59:02[s6-finish] syncing disks.
17/07/2017 09:59:04[s6-finish] sending all processes the TERM signal.
17/07/2017 09:59:07[s6-finish] sending all processes the KILL signal and exiting.
```
I believe that backup should continue but not exit.

**Comment by disaster37** [comment]
It's seems you not expose environnent variable about credential on your service ?

**Comment by Ilya-Kuchaev** [comment]
Exposed username, password and database. What if I want to backup ALL databases? Can script connect with the default postgres user?

**Comment by Ilya-Kuchaev** [comment]
Anyway, backup process should continue to proceed as for me.

**Comment by disaster37** [comment]
Hum, in the docker spirit, you must have one db per Postgres instance.
If you look the current template for Postgres, you don't expose as environnent variable POSTGRES_USER and POSTGRES_DB to dump all database

**Comment by Ilya-Kuchaev** [comment]
Nope.
You just have to try to dump all databases with the postgres user without password. Anyway, the backup shouldn't exit with the error. Just notify about it in output. IMHO

**Comment by piotrgiedziun** [comment]
I have resolved it in pull request #20.

**Comment by disaster37** [comment]
Hi,
Can you try the develop image to confirm me that the PR fix issue ?

**Comment by piotrgiedziun** [comment]
Hi,

here is the latest version that I'm using `piotrgiedziun/rancher-backup:fix_pg`
