### ISSUE TITLE
dangerous behavior with s6 fix-attrs when backuping local folder

### ISSUE THREAD

**Issue by fredleger** [disaster37/rancher-backup#26]
The following line 
https://github.com/disaster37/rancher-backup/blob/3e589e6e8948309dbb9fce8423707a68db8e98cd/root/etc/fix-attrs.d/01-backup-dir#L1 
is having a non wanted (from my point of view) behavior when used in conjonction with a local volume mount (that you do want to backup).

It will results in all your files ownership & rights being replaced by `backup 660`
This is quite dangerous and not expected

Why not having a separate `/data` folder to mount target volumes to be backuped by duplicity ?

**Comment by smurfy** [comment]
having the same issue, luckily i used ``:ro``  to mount the other volumes.
Problem here is that fix-attrs.d  throws a LOT of errors  and duplicity too due to permission errors.

**Comment by disaster37** [comment]
You are  right. I will remove the first line on 01-backup-dir and then launch the program as root to avoid access error.

**Comment by disaster37** [comment]
It's fix on `webcenter/rancher-backup:develop`.
