### ISSUE TITLE
Backup to EU S3 buckets do not work by default

### ISSUE THREAD

**Issue by mspanc** [disaster37/rancher-backup#27]
EU S3 buckets require v4 authentication scheme. Old v2 scheme is supported only in US and is deprecated.

The resolution is to use S3_USE_SIGV4=True env var.

As this is preferred scheme anyway, maybe it's good idea to add this to the rancher catalog entry.

**Comment by disaster37** [comment]
Thx for your contrib. It's now inlude on my catalog (webcenter-catalog) and available on next release.
