### ISSUE TITLE
Add the possibility to perform backup of Rancher database

### ISSUE THREAD

**Issue by disaster37** [disaster37/rancher-backup#4]
All database properties is set on https://rancher/v2-beta/settings.
So we can add the Rancher database dump before externalise the backup

**Comment by pwFoo** [comment]
Rancher DB backup would be nice! 👍

**Comment by disaster37** [comment]
You can now perform Rancher database dump before run backup with Duplicity on develop branch.

Please read the Readme on branch develop before test, because of there are so many breaking change compare to master branch.

You need to set the following environment variable:
- **BACKUP_rancher_db_host**: The rancher database IP/DNS (needed if you should perform Rancher database dump). No default value.
- **BACKUP_rancher_db_port**: The rancher database port (needed if you should perform Rancher database dump). Default is `3306`.
- **BACKUP_rancher_db_user**: The rancher database user (needed if you should perform Rancher database dump). Default is `rancher`.
- **BACKUP_rancher_db_password**: The rancher database password (needed if you should perform Rancher database dump). No default value.
- **BACKUP_rancher_db_name**: The rancher database name (needed if you should perform Rancher database dump). Default is `rancher`.
