### ISSUE TITLE
Rancher Catalog

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [disaster37/rancher-backup#8]
Any chance to see https://github.com/disaster37/community-catalog updated with the latest version?

**Comment by disaster37** [comment]
The PR must be merge on community catalog. 

https://github.com/rancher/community-catalog/pull/478

**Comment by Ilya-Kuchaev** [comment]
1.0.2 is not a latest version as I can see from https://github.com/disaster37/rancher-backup/releases
What are the required options to start it manually? Do you have the examples? Readme doesn't cover it.
Thanks!
