### ISSUE TITLE
Backup of mongodb does not work

### ISSUE THREAD

**Issue by 3cola** [disaster37/rancher-backup#9]
The backup of mongodb using mongodump fails.
There is a well known problem of permission with mongodump and it fails to write into the destination folder. You can work around it by removing th "--out {{DESTINATION}}", using the "--gzip --archive" that will print to standard output and writing to your destination like this "> {{DESTINATION}}/{{SCHEMA}}.gz".

**Comment by 3cola** [comment]
the command in mongo.yml should look loke this :
"mongodump --host %ip% --archive > %target_dir%/backup.archive"

**Comment by disaster37** [comment]
I will add this on mongo template:

```
--gzip --archive > {{ target_dir }}/databases.archive.gz
```

Thx for your share

**Comment by peXed** [comment]
Hello. I'm running in the premission problems.

Was this already fixed? If not, when will the fix be available and is there a way to fix it temporary in my setup?

Thank you very much.
